development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: rails
  password: longpassword
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: rails
  password: longpassword
  host: localhost
production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: rails
  password: longpassword
  host: localhost
